### ISSUE TITLE
How to include the library

### ISSUE THREAD

**Issue by Herz3h** [OpenVPN/openvpn3#48]
Hello,

I'm trying to use this library to create an simple openvpn client, however I don't really know how to include it properly into my c++ application. 

I have tried with following includepath : 
-Iopenvpn3/

With above I get a bunch of "Redefinition of X" (ServerEntry, etc...)

So I'm not sure how this library should be used. Should I use the classes inside openvpn3/openvpn/ only ? From what I understand in readme, I should be using the OpenVPNClient interface inside openvpn3/client/

Thanks in advance.

**Comment by Herz3h** [comment]
Never mind regarding the Redefinition error, I had <client/ovncli.hpp> included two times in different files. But now it tells me OPENVPN_PACKAGE_ID must be defined. And this turns out to be in the Android folder.

I intend to build application for OS X and Windows only, what am I doing wrong ?

**Comment by ordex** [comment]
we don't know what you are doing therefore it is not easy to guess what's wrong.
How about you share how you are compiling the library/binary and what is the exact output with the error?

**Comment by dsommers** [comment]
Try adding `#include <openvpn/common/platform.hpp>` first and then move `#include <client/ovpncli.cpp>` above the `openvpn/options/merge.hpp` include.

**Comment by Herz3h** [comment]
I have a new error now : 

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -lto_library /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib -dynamic -arch x86_64 -headerpad_max_install_names -macosx_version_min 10.10.0 -o vpn-bridge.app/Contents/MacOS/vpn-bridge -L/Users/Herz3h/Documents/VPNGUI-WINDOWS/src/mac/mbedtls/mbedtls-osx/library -framework Security -framework CoreFoundation -framework SystemConfiguration -framework IOKit -framework ApplicationServices -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -rpath @executable_path/Frameworks -rpath /Users/Herz3h/Qt/5.10.1/clang_64/lib main.o mainwindow.o client.o qrc_logojpl.o moc_mainwindow.o -lmbedtls /Users/Herz3h/Documents/VPNGUI-WINDOWS/src/mac/lz4/lz4-osx/lib/liblz4.a -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtNetwork -framework OpenGL -framework AGL -lc++ -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/lib/darwin/libclang_rt.osx.a -F/Users/Herz3h/Qt/5.10.1/clang_64/lib
duplicate symbol __ZN7openvpn9ClientAPI13OpenVPNClient16crypto_self_testEv in:
    main.o
    mainwindow.o
duplicate symbol __ZN7openvpn9ClientAPI13OpenVPNClient9copyrightEv in:
    main.o
    mainwindow.o
duplicate symbol __ZN7openvpn9ClientAPI13OpenVPNClient13on_disconnectEv in:
    main.o
    mainwindow.o
```

The errors keeps going on, I seem to have 204 duplicated symbols. I made sure I included ovpncli.cpp only once in my .h file

**Comment by Herz3h** [comment]
Is there anything I can do ? The problem once again seems to be that I have to include the .cpp file instead of an .hpp file. But that causes the duplicate symbols error.

**Comment by dsommers** [comment]
Please have a close look at how the reference client ([test/ovpncli/cli.cpp](https://github.com/OpenVPN/openvpn3/blob/master/test/ovpncli/cli.cpp)) does things.  Another reference point is the openvpn3-linux implementation ([openvpn3-service-client](https://github.com/OpenVPN/openvpn3-linux/blob/master/src/client/openvpn3-service-client.cpp), [core-client.hpp](https://github.com/OpenVPN/openvpn3-linux/blob/master/src/client/core-client.hpp)).  These two implementations manages to implement the client without any duplicated symbols.

It is hard to understand what is going wrong without seeing the whole picture as well, so without sharing your project with us, we will just be shooting blindly in the dark.

**Comment by Herz3h** [comment]
I already looked the cli.cpp before, I've tried having same includes/defines, but same result. I took a quick look at core-client.cpp but it seems they also include the ovpncli.cpp (which seems to be the root cause).

It seems odd to have to include a .cpp file for a library instead of .hpp... 

Here is the full compilation log which ends up giving me duplicated symbols: https://pastebin.com/1aLNstpL

**Comment by dsommers** [comment]
We need the full source code of your implementation too.  Plus it would help a lot if all the warnings and errors weren't in French.  We are also chasing a ghost here, as the earlier compiler warnings you showed here seems to be from a Mac running XCode, while this pastebin seems to be from a Windows box - which means: Quite different compiler environments.

In regards to the .cpp file inclusion. A file name is a file name, which is the argument given to #include, regardless of the extension.  There is nothing special about including a .cpp except of it being a bit unusual.  But it needs to be like this for other use cases this library has.

I believe the root cause is wrong order of #include statements.  And then you build several object files from .cpp files, where some of the same symbols ends up being in more object files, which then explodes when these objects files are getting linked together.  You need to figure out a way to untangle this, as it won't compile as it is now.

But since you're playing with Qt, also ensure that you use at least -std=c++11, preferably -std=c++14.  Depending on Qt versions, this might or might not work - I don't know how compliant your Qt targets are with those standards.

I'm closing this now, as this seems to be more a local implementation issue and not a bug in the OpenVPN 3 Core library.

**Comment by Herz3h** [comment]
Here is the fully source of the implementation : [https://github.com/Herz3h/VPNClient](VPNClient), I've tried on Windows and Mac, this repository is ready to be compiled on Windows with Qt 5.x (here is the [https://github.com/Herz3h/vpnclient/blob/master/client.cpp](client.cpp)

**Comment by dsommers** [comment]
I get "404 This is not the web page you are looking for." on both these URLs.

**Comment by dsommers** [comment]
Oh, wait ... the URLs are wrong, the "text version" of the URL works.

**Comment by Herz3h** [comment]
Ok sorry the link is fixed

**Comment by dsommers** [comment]
You have `#include <openvpn/io/io.hpp>` on line 6 in `client.h`.  Try moving that one below line 11.  But if you have more files including client.h which are built as separate object files, you will still most likely hit the duplicated symbols error.  This needs to be resolved differently as well.

**Comment by dsommers** [comment]
I also see you have: `#define OPENVPN_CORE_API_VISIBILITY_HIDEN`.  There's a typo here. It should say `HIDDEN` not `HIDEN`.

**Comment by Herz3h** [comment]
I've moved the `io.hpp` include below `ovpncli.hpp`, and fixed the typo. As for `client.h` it is included by `mainwindow.h` which in turn is included by `main.cpp`, what do you mean it should be "resolved differently" ?

**Comment by schwabe** [comment]
Generally OpenVPN3 core is a bit different than most libraries. The whole implementation is header only. 

To fix the problem you are seeing I would if possible for you include the openvpn header in *only one* c/c++ file and make only that file access openvpn3 directly and the rest of your program go that that class/file with function calls. We might fix openvpn3 in the future to be used more like a normal c++ library but at the moment that is the approach you need to take.

**Comment by Herz3h** [comment]
@schwave So the idea is to include the ovpncli.hpp ? Because I have tried that and I get [different errors](https://pastebin.com/Qh0nA1n9)

**Comment by dsommers** [comment]
No, you **must** use `ovpncli.cpp`.

**Comment by Herz3h** [comment]
So I have a `client.h` class which include the ovpncli.cpp and makes the implementation. Then `mainwindow.cpp` uses Client class and not OpenVPNClient class directly, but that's where I was before and had the duplicated symbols, so I'm confused regarding your last message.

**Comment by dsommers** [comment]
Your duplicated symbols issues is tied to

        duplicate symbol __ZN7openvpn9ClientAPI13OpenVPNClient16crypto_self_testEv in:
        main.o
        mainwindow.o

So both main.cpp and mainwindow.cpp is including the same openvpn3 header file somewhere in the chain.  This needs to be decoupled, so that only one of these source files includes `ovpncli.cpp`.

Or how I understand what @schwabe says, you have your own implementation of the "OpenVPN 3 Client class"  where the declaration is exported in a .hpp file, used by both main.cpp and mainwindow.cpp and the implementation is built separately from its own .cpp file.  When linking this together, you will only have the needed symbols defined in a single object file.

**Comment by dsommers** [comment]
And just to clarify an ugly detail in the last paragraph ... the declaration cannot include any openvpn3 header files, those needs to be included in the implementation file only.

**Comment by Herz3h** [comment]
So if my client.h (Client class) is the one I expose, It should not include any openvpn3 headers files (but rather the client.cpp should include those) right ? I have tried that, and symbols are duplicated still.... I'm sorry but I really don't understand how I should go about this. 

I have a my `client.h` class (inheriting OpenVPNClient) decalaration, the implementation is inside `client.cpp` (I have tried including openvpn3 headers here too instead of in the `client.h`, then my `mainwindow.h` includes the `client.h` and `main.cpp` includes `mainwindow.h`

**Comment by dsommers** [comment]
You might need to ensure that you do not expose any OpenVPN 3 related symbols at all in `client.h`.

As I see the current include chain in your current github repository (git master commit eb0c800fb77ce5c889b78daf74219c4ece14b1fa):

     * mainwindow.cpp includes:
        - mainwindow.h  includes:
           -  client.hpp  includes
                - ovpncli.cpp
     * main.cpp includes
           - mainwindow.h includes
                -  ui_mainwindow.h (no openvpn3 related includes)
                -  client.hpp includes:
                     - ovpncli.cpp

Here you see that `ovpncli.cpp` gets included twice, via separate `.cpp` files - which is compiled separately into separate object files, both containing the same symbols from `ovpncli.cpp`.  This is why client.hpp **cannot** include any openvpn3 source files, otherwise you will have duplicated symbols conflict, all pointing at `ovpncli.cpp`.

So you need to be sure that your `client.h` is completely openvpn3 agnostic, only exports its own declarations.  And the `client.cpp` which includes `ovpncli.cpp` with the needed implementation.  This needs to built separately (into it's own `client.o` object file) and then this object file can be linked together with `mainwindow.o` and `main.o` and the end result is your executable client.

**Comment by Herz3h** [comment]
I understand now, I've got it working. 

Thank you very much for the help 👍
