### ISSUE TITLE
client/CMakeFiles/ovpnclilib.dir/ovpncli.cpp.o

### ISSUE THREAD

**Issue by shensg** [OpenVPN/openvpn3#270]
# cmake --build .
[  1%] Building CXX object client/CMakeFiles/ovpnclilib.dir/ovpncli.cpp.o
In file included from /root/O3/core/cmake/../openvpn/pki/cclist.hpp:31:0,
                 from /root/O3/core/cmake/../openvpn/openssl/ssl/sslctx.hpp:59,
                 from /root/O3/core/cmake/../openvpn/init/engineinit.hpp:33,
                 from /root/O3/core/cmake/../openvpn/init/initprocess.hpp:35,
                 from /root/O3/core/client/ovpncli.cpp:90:
/root/O3/core/cmake/../openvpn/common/file.hpp:43:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
client/CMakeFiles/ovpnclilib.dir/build.make:69: recipe for target 'client/CMakeFiles/ovpnclilib.dir/ovpncli.cpp.o' failed
make[2]: *** [client/CMakeFiles/ovpnclilib.dir/ovpncli.cpp.o] Error 1
CMakeFiles/Makefile2:981: recipe for target 'client/CMakeFiles/ovpnclilib.dir/all' failed
make[1]: *** [client/CMakeFiles/ovpnclilib.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by flichtenheld** [comment]
Please document on which OS with with Toolchain you tried to compile this. Also please post the complete cmake output with "--verbose".

**Comment by shensg** [comment]
Build on Ubuntu18.04_x86_64 system

**Comment by shensg** [comment]
Cmake '-- verbose' cannot run

Output:
$ cmake --build . --verbose
Unknown argument --verbose
Usage: cmake --build <dir> [options] [-- [native-options]]
Options:
  <dir>          = Project binary directory to be built.
  --target <tgt> = Build <tgt> instead of default targets.
                   May only be specified once.
  --config <cfg> = For multi-configuration tools, choose <cfg>.
  --clean-first  = Build target 'clean' first, then build.
                   (To clean only, use --target 'clean'.)
  --use-stderr   = Ignored.  Behavior is default in CMake >= 3.0.
  --             = Pass remaining options to the native tool.

**Comment by shensg** [comment]
Resolved, The plan is as follows:
modify  /root/O3/core/cmake/../openvpn/common/file.hpp  '#include <filesystem>' to '#include <experimental/filesystem>'

**Comment by schwabe** [comment]
Our library requires C++17 and the filesystem header is part of that https://en.cppreference.com/w/cpp/filesystem

The code there even has guards around that feature only being used on C++17 `#if __cplusplus >= 201703L`. So this is more some broken C++17 on your system

**Comment by flichtenheld** [comment]
Ubuntu 18.04 also provides a gcc 8 as an alternative to the system default gcc 7. You can install it with "apt install g++-8" and then build with environment CXX=g++-8 CC=gcc-8 AR=gcc-ar-8 RANLIB=gcc-ranlib-8
That build was working before we removed the Ubuntu 18.04 builds completely.

You really shouldn't use Ubuntu 18.04 anymore, of course.

**Comment by shensg** [comment]
Many thanks, I just want to test it out.

**Comment by shensg** [comment]
I am trying to run command: sudo test/ovpncli/ovpncli client.ovpn route nopull

Throw an error:
Main thread exception: need creds

**Comment by shensg** [comment]
We have found the cause of the abnormality 'Main thread exception: need creds'. It turns out that authentication requires configuring a user password
